openapi: 3.0.2
info:
  title: pidwin-fs-take-home-project
  version: 0.0.1
  description: Pidwin Full Stack Backend Take-Home Project
servers:
  - url: http://localhost:5000/
paths:
  $ref: ./paths/_index.yaml
components:
  schemas:
    $ref: ./schemas/_index.yaml
  securitySchemes:
    $ref: ./security-schemes/_index.yaml
